sonar.projectKey=eco-frontend
sonar.projectName=ecotrack-frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_adf978631e681a66d65c86e80639a7a94eb873b0

# Carpeta raíz porque tus componentes y app están en la raíz
sonar.sources=.

# Carpetas específicas que sí queremos escanear
sonar.inclusions=app/**/*.ts,app/**/*.tsx,components/**/*.ts,components/**/*.tsx,hooks/**/*.ts,hooks/**/*.tsx,lib/**/*.ts

# Carpetas y archivos basura que vamos a ignorar por completo
sonar.exclusions=node_modules/**,.next/**,out/**,public/**,*.config.js,*.config.mjs,next-env.d.ts,**/*.spec.ts,**/*.test.ts

sonar.coverage.exclusions=app/**,components/ui/**,components/AppLayout.tsx,components/AdminCenterForm.tsx,components/AdminCouponForm.tsx,components/CollectionCenterQrPanel.tsx,components/FriendCard.tsx,components/ProtectedAppLayout.tsx,components/ScrollToTopLink.tsx,next-env.d.ts,**/*.spec.*,**/*.test.*

sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Ruta al archivo de configuración de TypeScript
sonar.typescript.tsconfigPath=tsconfig.json